services:
  client:
    build: ./client
    # entrypoint: ["/bin/sh", "-c"]
    command: npm run test
    restart: always
    environment:
      - VITE_API_URL=http://localhost:7100/graph
    volumes:
      - ./client:/app/

  reverse_proxy:
    image: nginx
    ports:
      - 7100:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - client
