name: Run All API TEST (Integration)

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - predeploy

jobs:
  tests-api:
    name: Run integration test on API Graph / TypeORm / PostGres
    runs-on: ubuntu-latest

    steps:
      - name: Step 1 Check out git repo
        uses: actions/checkout@v4

      - name: Setup Docker
        uses: docker/setup-buildx-action@v2

      - name: Run test
        run: |
          docker compose -f docker-compose.test.yml up --build --exit-code-from staging_api_data

  tests-client:
    name: Run integration tests on client
    runs-on: ubuntu-latest

    steps:
      - name: Step 1 Check out git repo
        uses: actions/checkout@v4

      - name: Cache Dependencies
        uses: actions/cache@v3
        with:
          path: |
            ./client/node_modules
          key: ${{ runner.os }}-${{  hashfiles('./client/package-lock.json')}}

      - name: Install package dependence
        run: cd client && npm install

      - name: Run integration test on client
        run: cd ./client && npm run integration-test
